* DMD DiaRY
DiaRY and Research-log keeping utility.

DRY aims to make it simple to keep and annotate daily video/notes as a personal-diary and research log. All of the files lives in an encrypted directory. This is a WIP project and for now it only suits my basic needs.

Some operations still needs do be done manually, but the future goal
is the possibility to rely completely on this *tool to keep tracks of
the complete project/research/life, based on the usecase.

 * and on its emacs integration that will come after this tool reach a
   minimal stable version

** FEATURES
- Create and delete diary entries (note and video)
- List and show entries
- Manage multiple diaries (project diary, daily, public)
- Full diary encryption
- WIP bash autocompletion

** USAGE
#+begin_src shell
  dry init #initialize a path on current directory
  dry add video # register a video on current diary (now)
  dry add note # add a text note on current diary (now)

  dry list date/+-timespan/today/yesterday # list entry in specified time span

  dry show id # show note by id
  dry play id # play video by id
  dry delete id/date/span #delete entry by id
#+end_src

** DEPENDENCIES
- ffmpeg
- encfs
- less
- exa

** INSTALLATION
To install dry clone the repo and run the following inside the repo's root

#+begin_src shell
cd dmd-diary
sudo make install
#+end_src

Than take a look at the config file and set your preferred values

** UNINSTALL
To remove dry got inside the ~dmd-diary~ directory than run

#+begin_src shell
sudo make uninstall
#+end_src

** CONFIG
Possible config paths (can have multiple configs)
- =~/.config/dry.yml=
- =~/dry.yml=
- =/etc/dry.yml=

#+begin_src 
default_diary = "diary";
text_editor = "emacsclient -t";
video_player = "mpv";
default_dir = "/home/user/.dry/storage"; # this path needs to be absolute
#+end_src

** INTERNALS
Dry is a pretty simple wrapper for a series of CLI operations, thus it could be written in something simple

** TODOS
- fix: write reference after successfully having saved the video
- fix: exit if encfs fails to open properly
- fix: ffmpeg not properly initialize webcam
- refactor: general cleanup
- feat: Open/close diary to manual modify
- feat: add diary attachments (dry new attach path)
- feat: export diary to unencrypt form
- improve: CLI, use params to permit permutations (-m "message", -d YYYY-MM-DD) (argp.h)
- feat: more config for user to customize
- improve: main and parsing modularity in arguments parsing
- feat: chiper enc/dec optimization (modular fs? exclude big files?  encfs support?)
- feat: make encryption optional
- fix: fix bash completion

Next steps:
- feat: configure markdown (and others) as a possible choice for markup langs
- feat: filters
- improve: new note, video/attachments reference inserted into notes of day
- feat: mobile application integration
- feat: permits to embed screencast and screenshots, as well as other formats, to the video entry
- feat: permits to customize an overlay for the video entry in config file
- sec: security code review, focalized on enc and dec of data, as race condition that could let the db open
- feat: add colors

Add configurations:
- video
  - size
  - format
  - webcam
  - microphone
- markdown formats (see =configure markdown=)
- display note command (=cat=, =less=, etc...)


** NOTES

For initilizing a new diary ~init~ is used
#+begin_src shell
  dry init <diary_name>
#+end_src

To create new content issue the ~add~ command, bot will create a reference in the current daily entry, that is created if not exists, marking hour of the day.
- video -  records a video, uses webcam and mic connected to the PC, also add a reference to the video to the daily entry
- note - add text to the entry
#+begin_src shell
  dry new <video|note>
#+end_src

To explore captured content just use ~list~ or ~show~
- ~list~ - will list the content relative to the entries specified by the query
- ~show~ - will print out a daily entry or reproduce the attachment
#+begin_src shell
  dry <list|show> <today|yesterday|yyyy-mm-dd>
#+end_src

Deleting a diary entity is done trought the usage of ~delete~
#+begin_src shell
  dry delete <id> <diary_name>
#+end_src
